import zlib from "node:zlib";
import { PDFParse } from "pdf-parse";
import type { ResumeBuilderData } from "@/lib/validation";

/**
 * Extracts plain text from builderData
 */
export function compileResumeBuilderText(
  data?: ResumeBuilderData | null,
): string {
  if (!data) return "";
  const parts: string[] = [];
  const {
    personalInfo,
    summary,
    experiences,
    educations,
    skillGroups,
    projects,
    certifications,
  } = data;

  if (personalInfo?.fullName) {
    parts.push(personalInfo.fullName);
    if (personalInfo.headline) parts.push(personalInfo.headline);
    const contacts = [
      personalInfo.email,
      personalInfo.phone,
      personalInfo.location,
      personalInfo.linkedin,
      personalInfo.github,
      personalInfo.website,
    ].filter(Boolean);
    if (contacts.length > 0) parts.push(contacts.join(" | "));
  }

  if (summary) {
    parts.push(`\nPROFESSIONAL SUMMARY\n${summary}`);
  }

  if (experiences && experiences.length > 0) {
    parts.push("\nEXPERIENCE");
    for (const exp of experiences) {
      const line = `${exp.role || "Role"} at ${exp.company || "Company"}${exp.location ? `, ${exp.location}` : ""} (${exp.startDate || ""} - ${exp.isCurrent ? "Present" : exp.endDate || "Present"})`;
      parts.push(line);
      if (exp.description) parts.push(exp.description);
      if (exp.highlights && exp.highlights.length > 0) {
        parts.push(exp.highlights.map((h) => `• ${h}`).join("\n"));
      }
    }
  }

  if (educations && educations.length > 0) {
    parts.push("\nEDUCATION");
    for (const edu of educations) {
      parts.push(
        `${edu.degree || ""}${edu.fieldOfStudy ? ` in ${edu.fieldOfStudy}` : ""} - ${edu.institution || ""} (${edu.startDate || ""} - ${edu.endDate || ""})`,
      );
      if (edu.honors) parts.push(`Honors: ${edu.honors}`);
    }
  }

  if (skillGroups && skillGroups.length > 0) {
    parts.push("\nSKILLS");
    for (const group of skillGroups) {
      if (group.skills && group.skills.length > 0) {
        parts.push(
          `${group.category || "Technical Skills"}: ${group.skills.join(", ")}`,
        );
      }
    }
  }

  if (projects && projects.length > 0) {
    parts.push("\nPROJECTS");
    for (const proj of projects) {
      parts.push(`${proj.title || "Project"}: ${proj.description || ""}`);
      if (proj.techStack && proj.techStack.length > 0) {
        parts.push(`Technologies: ${proj.techStack.join(", ")}`);
      }
    }
  }

  if (certifications && certifications.length > 0) {
    parts.push("\nCERTIFICATIONS");
    for (const cert of certifications) {
      parts.push(
        `${cert.name || "Certification"} - ${cert.issuer || ""} (${cert.date || ""})`,
      );
    }
  }

  return parts.join("\n").trim();
}

/**
 * Decodes standard PDF escape sequences and octal character codes
 */
function decodePdfString(str: string): string {
  if (!str) return "";
  return str
    .replace(/\\([0-7]{1,3})/g, (_, oct) =>
      String.fromCharCode(parseInt(oct, 8)),
    )
    .replace(/\\n/g, "\n")
    .replace(/\\r/g, "\r")
    .replace(/\\t/g, "\t")
    .replace(/\\b/g, " ")
    .replace(/\\f/g, " ")
    .replace(/\\([()\\])/g, "$1");
}

/**
 * Decodes PDF hex-encoded strings e.g. <48656c6c6f>
 */
function decodePdfHexString(hex: string): string {
  if (!hex) return "";
  let decoded = "";
  for (let i = 0; i < hex.length; i += 2) {
    const code = parseInt(hex.substring(i, i + 2), 16);
    if (code >= 32 && code <= 126) {
      decoded += String.fromCharCode(code);
    }
  }
  return decoded;
}

/**
 * Robust stream extractor for PDF buffers that decompresses FlateDecode
 * (zlib) streams and decodes text operators (Tj, TJ, hex strings).
 * Works reliably on standard PDFs generated by Word, Canva, LaTeX, and Google Docs.
 */
function extractTextFromPdfStreams(buffer: Buffer): string {
  try {
    const textPieces: string[] = [];
    let pos = 0;

    while (pos < buffer.length) {
      const streamStart = buffer.indexOf("stream", pos);
      if (streamStart === -1) break;

      // Look back for stream dictionary header (detect compression)
      const headerStart = Math.max(0, streamStart - 500);
      const header = buffer.slice(headerStart, streamStart).toString("binary");
      const isFlate =
        /Filter\s*\/FlateDecode|Filter\s*\[\s*\/FlateDecode/i.test(header);

      // Find content start (skip 'stream\r\n' or 'stream\n')
      let contentStart = streamStart + 6;
      if (buffer[contentStart] === 0x0d && buffer[contentStart + 1] === 0x0a) {
        contentStart += 2;
      } else if (
        buffer[contentStart] === 0x0a ||
        buffer[contentStart] === 0x0d
      ) {
        contentStart += 1;
      }

      const streamEnd = buffer.indexOf("endstream", contentStart);
      if (streamEnd === -1) break;

      let content = buffer.slice(contentStart, streamEnd);
      if (content.length > 0 && content[content.length - 1] === 0x0a) {
        content = content.slice(0, -1);
      }
      if (content.length > 0 && content[content.length - 1] === 0x0d) {
        content = content.slice(0, -1);
      }

      let decompressed = "";
      if (isFlate) {
        try {
          decompressed = zlib.inflateSync(content).toString("binary");
        } catch {
          try {
            decompressed = zlib.inflateRawSync(content).toString("binary");
          } catch {
            decompressed = content.toString("binary");
          }
        }
      } else {
        decompressed = content.toString("binary");
      }

      if (decompressed) {
        // 1. Literal text: (text) Tj
        const tjMatches = decompressed.matchAll(/\(([^)]*)\)\s*Tj/g);
        for (const m of tjMatches) {
          if (m[1]) textPieces.push(decodePdfString(m[1]));
        }

        // 2. Text array: [(t) 10 (e) 5 (x) (t)] TJ
        const tjArrayMatches = decompressed.matchAll(/\[(.*?)\]\s*TJ/g);
        for (const m of tjArrayMatches) {
          if (m[1]) {
            const inners = m[1].matchAll(/\(([^)]*)\)|<([0-9a-fA-F]+)>/g);
            for (const im of inners) {
              if (im[1]) {
                textPieces.push(decodePdfString(im[1]));
              } else if (im[2]) {
                const decodedHex = decodePdfHexString(im[2]);
                if (decodedHex) textPieces.push(decodedHex);
              }
            }
          }
        }

        // 3. Hex string text: <48656c6c6f> Tj
        const hexTjMatches = decompressed.matchAll(/<([0-9a-fA-F]+)>\s*Tj/g);
        for (const m of hexTjMatches) {
          if (m[1]) {
            const decodedHex = decodePdfHexString(m[1]);
            if (decodedHex) textPieces.push(decodedHex);
          }
        }
      }

      pos = streamEnd + 9;
    }

    const clean = textPieces
      .join(" ")
      .replace(/[^\x20-\x7E\n\r\t]/g, " ")
      .replace(/\s+/g, " ")
      .trim();

    return clean;
  } catch {
    return "";
  }
}

/**
 * Extracts plain text from a PDF Buffer using multiple complementary techniques:
 * 1. PDFParse (pdfjs-dist engine)
 * 2. Native zlib FlateDecode stream decompressor with Tj / TJ operator parser
 * 3. Printable ASCII block scan fallback
 */
export async function extractTextFromPdfBuffer(
  buffer: Buffer,
): Promise<string> {
  // Strategy 1: Attempt standard PDFParse engine
  try {
    const parser = new PDFParse({
      data: new Uint8Array(buffer),
      verbosity: 0,
    });
    const result = await parser.getText();
    const text = typeof result === "string" ? result : result?.text || "";

    if (text && text.trim().length > 60) {
      return text.trim();
    }
  } catch (err) {
    console.warn(
      "[PDF Parser] PDFParse error, falling back to Flate stream parsing:",
      err,
    );
  }

  // Strategy 2: Decompress FlateDecode streams and parse PDF text operators
  const streamText = extractTextFromPdfStreams(buffer);
  if (streamText && streamText.length > 50) {
    return streamText;
  }

  // Strategy 3: Last resort printable ASCII strings
  try {
    const str = buffer.toString("utf-8");
    const clean = str
      .replace(/[^\x20-\x7E\n\r\t]/g, " ")
      .replace(/\s+/g, " ")
      .trim();
    if (clean.length > 80) {
      return clean.slice(0, 10000);
    }
  } catch {
    // ignore
  }

  return "";
}

/**
 * Universally extract resume text from any source:
 * - base64 string
 * - remote URL (Cloudinary / HTTPS)
 * - data URL
 * - raw text
 * - builderData
 */
export async function extractResumeTextUniversal(options: {
  rawText?: string | null;
  fileBase64?: string | null;
  fileUrl?: string | null;
  builderData?: ResumeBuilderData | null;
  fileName?: string | null;
}): Promise<{
  text: string;
  inlinePdfData: { mimeType: string; data: string } | null;
}> {
  const { rawText, fileBase64, fileUrl, builderData, fileName } = options;

  let text = "";
  let inlinePdfData: { mimeType: string; data: string } | null = null;

  // 1. If rawText already exists and has substantial content
  if (rawText && rawText.trim().length > 30) {
    text = rawText.trim();
  }

  // 2. If builderData exists
  if (!text && builderData) {
    text = compileResumeBuilderText(builderData);
  }

  // 3. If fileBase64 is passed (upload mode)
  if (fileBase64) {
    const cleanBase64 = fileBase64.replace(/^data:[^;]+;base64,/, "");
    const isPdf =
      fileBase64.includes("application/pdf") ||
      fileName?.toLowerCase().endsWith(".pdf") ||
      cleanBase64.startsWith("JVBERi"); // %PDF- in base64

    if (isPdf) {
      inlinePdfData = {
        mimeType: "application/pdf",
        data: cleanBase64,
      };
      if (!text) {
        try {
          const buffer = Buffer.from(cleanBase64, "base64");
          text = await extractTextFromPdfBuffer(buffer);
        } catch (err) {
          console.warn(
            "[Resume Text Extractor] Failed to extract from fileBase64:",
            err,
          );
        }
      }
    } else if (!text) {
      try {
        text = Buffer.from(cleanBase64, "base64").toString("utf-8");
      } catch {
        text = cleanBase64;
      }
    }
  }

  // 4. If fileUrl is a data URL
  if (fileUrl?.startsWith("data:")) {
    const cleanBase64 = fileUrl.replace(/^data:[^;]+;base64,/, "");
    if (
      fileUrl.includes("application/pdf") ||
      cleanBase64.startsWith("JVBERi")
    ) {
      inlinePdfData = {
        mimeType: "application/pdf",
        data: cleanBase64,
      };
      if (!text) {
        try {
          const buffer = Buffer.from(cleanBase64, "base64");
          text = await extractTextFromPdfBuffer(buffer);
        } catch (err) {
          console.warn(
            "[Resume Text Extractor] Failed to extract from data URL:",
            err,
          );
        }
      }
    } else if (!text) {
      try {
        text = Buffer.from(cleanBase64, "base64").toString("utf-8");
      } catch {
        // ignore
      }
    }
  }

  // 5. If fileUrl is remote URL (e.g. Cloudinary) and text is still empty
  if (!text && fileUrl && fileUrl.startsWith("http")) {
    try {
      const res = await fetch(fileUrl);
      if (res.ok) {
        const arrayBuf = await res.arrayBuffer();
        const buffer = Buffer.from(arrayBuf);
        const isPdf =
          fileUrl.toLowerCase().includes(".pdf") ||
          buffer.slice(0, 4).toString() === "%PDF";

        if (isPdf) {
          const base64 = buffer.toString("base64");
          inlinePdfData = {
            mimeType: "application/pdf",
            data: base64,
          };
          text = await extractTextFromPdfBuffer(buffer);
        } else {
          text = buffer.toString("utf-8");
        }
      }
    } catch (err) {
      console.warn(
        "[Resume Text Extractor] Could not fetch remote fileUrl:",
        err,
      );
    }
  }

  return { text: text.trim(), inlinePdfData };
}
