export interface SeedTemplateData {
  slug: string;
  name: string;
  subtitle: string;
  description: string;
  category: "tech" | "creative" | "executive" | "general";
  layoutArchetype:
    | "single_column"
    | "sidebar_left"
    | "executive_classic"
    | "minimal_tech";
  badge?: string;
  isPro: boolean;
  tokenCost: number;
  defaultTheme: {
    accentColor: string;
    fontFamily: "sans" | "serif" | "mono";
    layoutDensity: "compact" | "normal" | "spacious";
  };
  isActive: boolean;
  sortOrder: number;
}

export const TOP_50_RECRUITER_TEMPLATES: SeedTemplateData[] = [
  // ==========================================
  // 1-15: SOFTWARE & TECH (15 templates)
  // ==========================================
  {
    slug: "modern",
    name: "Modern Clean",
    subtitle: "Recommended for Tech & Corporate",
    description:
      "Sleek single-column layout with subtle accent headers, optimal ATS machine readability, and clear chronological flow.",
    category: "general",
    layoutArchetype: "single_column",
    badge: "Popular",
    isPro: false,
    tokenCost: 0,
    defaultTheme: {
      accentColor: "#4f46e5",
      fontFamily: "sans",
      layoutDensity: "normal",
    },
    isActive: true,
    sortOrder: 1,
  },
  {
    slug: "tech",
    name: "Tech Minimalist",
    subtitle: "Software Engineers & Data Science",
    description:
      "Developer-focused layout featuring categorized skill chips, repository & live demo links, and modern monospace accent tags.",
    category: "tech",
    layoutArchetype: "minimal_tech",
    badge: "PRO",
    isPro: true,
    tokenCost: 10,
    defaultTheme: {
      accentColor: "#059669",
      fontFamily: "mono",
      layoutDensity: "normal",
    },
    isActive: true,
    sortOrder: 2,
  },
  {
    slug: "silicon-valley-engineer",
    name: "Silicon Valley Engineer",
    subtitle: "FAANG & Tier-1 Tech Scale",
    description:
      "Designed specifically for senior engineers and engineering leaders targeting Google, Meta, and Apple with high-density impact metrics.",
    category: "tech",
    layoutArchetype: "single_column",
    badge: "FAANG",
    isPro: false,
    tokenCost: 0,
    defaultTheme: {
      accentColor: "#2563eb",
      fontFamily: "sans",
      layoutDensity: "normal",
    },
    isActive: true,
    sortOrder: 3,
  },
  {
    slug: "full-stack-architect",
    name: "Full-Stack Architect",
    subtitle: "Web, Distributed Systems & API Leads",
    description:
      "Highlights dual frontend/backend proficiencies, system architecture benchmarks, and microservices technical stacks.",
    category: "tech",
    layoutArchetype: "minimal_tech",
    badge: "Top Pick",
    isPro: true,
    tokenCost: 10,
    defaultTheme: {
      accentColor: "#7c3aed",
      fontFamily: "sans",
      layoutDensity: "normal",
    },
    isActive: true,
    sortOrder: 4,
  },
  {
    slug: "cloud-devops-pro",
    name: "Cloud & DevOps Pro",
    subtitle: "AWS, Kubernetes, SRE & Platform",
    description:
      "Tailored for infrastructure engineers featuring dedicated cloud certifications, uptime metrics, and CI/CD pipeline automation stats.",
    category: "tech",
    layoutArchetype: "single_column",
    badge: "",
    isPro: false,
    tokenCost: 0,
    defaultTheme: {
      accentColor: "#0284c7",
      fontFamily: "mono",
      layoutDensity: "normal",
    },
    isActive: true,
    sortOrder: 5,
  },
  {
    slug: "ai-ml-scientist",
    name: "AI & Machine Learning Scientist",
    subtitle: "LLMs, Computer Vision & Data Research",
    description:
      "Emphasizes PyTorch/TensorFlow stacks, research publication citations, model training benchmarks, and Kaggle/arXiv contributions.",
    category: "tech",
    layoutArchetype: "minimal_tech",
    badge: "PRO",
    isPro: true,
    tokenCost: 10,
    defaultTheme: {
      accentColor: "#059669",
      fontFamily: "mono",
      layoutDensity: "compact",
    },
    isActive: true,
    sortOrder: 6,
  },
  {
    slug: "open-source-contributor",
    name: "Open Source Contributor",
    subtitle: "OSS Authors & Core Maintainers",
    description:
      "Features prominent GitHub repository stats, star counts, npm package downloads, and major community contribution logs.",
    category: "tech",
    layoutArchetype: "sidebar_left",
    badge: "PRO",
    isPro: true,
    tokenCost: 10,
    defaultTheme: {
      accentColor: "#4f46e5",
      fontFamily: "sans",
      layoutDensity: "normal",
    },
    isActive: true,
    sortOrder: 7,
  },
  {
    slug: "cyber-security-analyst",
    name: "Cyber Security Analyst",
    subtitle: "SecOps, Penetration Testing & CISSP",
    description:
      "Structured for security professionals with dedicated compliance frameworks (SOC2, ISO, HIPAA) and vulnerability disclosure records.",
    category: "tech",
    layoutArchetype: "single_column",
    badge: "",
    isPro: false,
    tokenCost: 0,
    defaultTheme: {
      accentColor: "#0f172a",
      fontFamily: "mono",
      layoutDensity: "normal",
    },
    isActive: true,
    sortOrder: 8,
  },
  {
    slug: "data-systems-engineer",
    name: "Data Systems Engineer",
    subtitle: "ETL Pipelines, Snowflake & BigQuery",
    description:
      "Prioritizes data pipeline throughput (TB/day), query latency optimizations, and database cluster architectures.",
    category: "tech",
    layoutArchetype: "single_column",
    badge: "",
    isPro: false,
    tokenCost: 0,
    defaultTheme: {
      accentColor: "#0d9488",
      fontFamily: "sans",
      layoutDensity: "normal",
    },
    isActive: true,
    sortOrder: 9,
  },
  {
    slug: "mobile-developer",
    name: "Mobile App Engineer",
    subtitle: "iOS (Swift) & Android (Kotlin/Flutter)",
    description:
      "Highlights App Store release metrics, active monthly users (MAU), store ratings, and offline-first mobile architecture.",
    category: "tech",
    layoutArchetype: "sidebar_left",
    badge: "PRO",
    isPro: true,
    tokenCost: 10,
    defaultTheme: {
      accentColor: "#2563eb",
      fontFamily: "sans",
      layoutDensity: "normal",
    },
    isActive: true,
    sortOrder: 10,
  },
  {
    slug: "embedded-firmware",
    name: "Embedded & IoT Engineer",
    subtitle: "C/C++, RTOS, Hardware Integration",
    description:
      "Focuses on memory-constrained microcontroller architectures, board bring-up, communication protocols (SPI, I2C, CAN).",
    category: "tech",
    layoutArchetype: "single_column",
    badge: "",
    isPro: false,
    tokenCost: 0,
    defaultTheme: {
      accentColor: "#334155",
      fontFamily: "mono",
      layoutDensity: "compact",
    },
    isActive: true,
    sortOrder: 11,
  },
  {
    slug: "sre-specialist",
    name: "Site Reliability Engineer (SRE)",
    subtitle: "Four Golden Signals, SLOs & Chaos Testing",
    description:
      "Built for reliability engineers emphasizing 99.99% availability tracking, incident MTTR reductions, and post-mortem ownership.",
    category: "tech",
    layoutArchetype: "minimal_tech",
    badge: "PRO",
    isPro: true,
    tokenCost: 10,
    defaultTheme: {
      accentColor: "#dc2626",
      fontFamily: "mono",
      layoutDensity: "normal",
    },
    isActive: true,
    sortOrder: 12,
  },
  {
    slug: "frontend-ui-architect",
    name: "Frontend UI Architect",
    subtitle: "React 19, Next.js & Performance Core Web Vitals",
    description:
      "Demonstrates lighthouse scores, component library scalability, micro-frontends, and accessible design system implementations.",
    category: "tech",
    layoutArchetype: "single_column",
    badge: "Trending",
    isPro: false,
    tokenCost: 0,
    defaultTheme: {
      accentColor: "#4f46e5",
      fontFamily: "sans",
      layoutDensity: "normal",
    },
    isActive: true,
    sortOrder: 13,
  },
  {
    slug: "backend-microservices",
    name: "Backend Microservices Lead",
    subtitle: "Go, Java, High-Concurreny & Kafka",
    description:
      "Focuses on low-latency RPC APIs, distributed transaction guarantees, caching layers, and database sharding techniques.",
    category: "tech",
    layoutArchetype: "single_column",
    badge: "",
    isPro: false,
    tokenCost: 0,
    defaultTheme: {
      accentColor: "#0f172a",
      fontFamily: "sans",
      layoutDensity: "normal",
    },
    isActive: true,
    sortOrder: 14,
  },
  {
    slug: "game-engine-developer",
    name: "Game Engine Developer",
    subtitle: "Unreal Engine, Unity & Graphics Shaders",
    description:
      "Highlights rendering pipeline optimizations, 60fps physics budgets, shader programming, and AAA title credits.",
    category: "tech",
    layoutArchetype: "minimal_tech",
    badge: "PRO",
    isPro: true,
    tokenCost: 10,
    defaultTheme: {
      accentColor: "#9333ea",
      fontFamily: "mono",
      layoutDensity: "normal",
    },
    isActive: true,
    sortOrder: 15,
  },

  // ==========================================
  // 16-27: PRODUCT & DESIGN (12 templates)
  // ==========================================
  {
    slug: "creative",
    name: "Creative Sidebar",
    subtitle: "Designers, Product & Marketing",
    description:
      "Contemporary 2-column layout with an eye-catching contact and skills sidebar, paired with an expansive career timeline.",
    category: "creative",
    layoutArchetype: "sidebar_left",
    badge: "PRO",
    isPro: true,
    tokenCost: 10,
    defaultTheme: {
      accentColor: "#2563eb",
      fontFamily: "sans",
      layoutDensity: "normal",
    },
    isActive: true,
    sortOrder: 16,
  },
  {
    slug: "product-manager-elite",
    name: "Product Manager Elite",
    subtitle: "Roadmaps, Retention & Cross-Functional Teams",
    description:
      "Structures accomplishments with the Google XYZ formula: accomplished [X], measured by [Y], by doing [Z] for PM hiring committees.",
    category: "creative",
    layoutArchetype: "single_column",
    badge: "Top Pick",
    isPro: false,
    tokenCost: 0,
    defaultTheme: {
      accentColor: "#4f46e5",
      fontFamily: "sans",
      layoutDensity: "normal",
    },
    isActive: true,
    sortOrder: 17,
  },
  {
    slug: "ui-ux-design-lead",
    name: "UI/UX Design Lead",
    subtitle: "Figma Systems, User Research & Design Thinking",
    description:
      "Balances typography hierarchy, case study summaries, user testing metrics, and design-to-engineering handoff success.",
    category: "creative",
    layoutArchetype: "sidebar_left",
    badge: "PRO",
    isPro: true,
    tokenCost: 10,
    defaultTheme: {
      accentColor: "#ec4899",
      fontFamily: "sans",
      layoutDensity: "normal",
    },
    isActive: true,
    sortOrder: 18,
  },
  {
    slug: "growth-product-specialist",
    name: "Growth Product Specialist",
    subtitle: "A/B Testing, Activation & Viral Loops",
    description:
      "Tailored for growth engineers and PMs focusing on CAC, LTV, conversion rate lifts, and experimentation velocity.",
    category: "creative",
    layoutArchetype: "single_column",
    badge: "",
    isPro: false,
    tokenCost: 0,
    defaultTheme: {
      accentColor: "#16a34a",
      fontFamily: "sans",
      layoutDensity: "normal",
    },
    isActive: true,
    sortOrder: 19,
  },
  {
    slug: "brand-identity-designer",
    name: "Brand Identity Designer",
    subtitle: "Art Direction, Typography & Packaging",
    description:
      "Elegant minimalist layout with ample whitespace and refined typography, favored by creative studios and fashion brands.",
    category: "creative",
    layoutArchetype: "sidebar_left",
    badge: "PRO",
    isPro: true,
    tokenCost: 10,
    defaultTheme: {
      accentColor: "#0f172a",
      fontFamily: "serif",
      layoutDensity: "spacious",
    },
    isActive: true,
    sortOrder: 20,
  },
  {
    slug: "design-systems-architect",
    name: "Design Systems Architect",
    subtitle: "Tokens, Accessibility (a11y) & Component Kits",
    description:
      "Demonstrates multi-platform component standardization, WCAG compliance auditing, and developer adoption percentages.",
    category: "creative",
    layoutArchetype: "single_column",
    badge: "",
    isPro: false,
    tokenCost: 0,
    defaultTheme: {
      accentColor: "#6366f1",
      fontFamily: "sans",
      layoutDensity: "normal",
    },
    isActive: true,
    sortOrder: 21,
  },
  {
    slug: "technical-pm",
    name: "Technical Product Manager (TPM)",
    subtitle: "API Platforms, Integrations & Cloud Infrastructure",
    description:
      "Bridges business impact with engineering depth, highlighting SDK adoption, API uptime, and developer platform ecosystems.",
    category: "creative",
    layoutArchetype: "single_column",
    badge: "PRO",
    isPro: true,
    tokenCost: 10,
    defaultTheme: {
      accentColor: "#0284c7",
      fontFamily: "sans",
      layoutDensity: "normal",
    },
    isActive: true,
    sortOrder: 22,
  },
  {
    slug: "product-marketing-director",
    name: "Product Marketing Director",
    subtitle: "Go-To-Market (GTM), Positioning & Messaging",
    description:
      "Emphasizes product launch revenue, competitive battlecard adoption, analyst relations (Gartner/Forrester), and inbound pipeline.",
    category: "creative",
    layoutArchetype: "single_column",
    badge: "",
    isPro: false,
    tokenCost: 0,
    defaultTheme: {
      accentColor: "#ea580c",
      fontFamily: "sans",
      layoutDensity: "normal",
    },
    isActive: true,
    sortOrder: 23,
  },
  {
    slug: "motion-media-designer",
    name: "Interactive & Motion Designer",
    subtitle: "3D Animation, After Effects & WebGL",
    description:
      "Features showreel links, interactive canvas achievements, micro-interaction design, and client campaign metrics.",
    category: "creative",
    layoutArchetype: "sidebar_left",
    badge: "PRO",
    isPro: true,
    tokenCost: 10,
    defaultTheme: {
      accentColor: "#9333ea",
      fontFamily: "sans",
      layoutDensity: "normal",
    },
    isActive: true,
    sortOrder: 24,
  },
  {
    slug: "content-strategist",
    name: "Content & Copy Strategist",
    subtitle: "Brand Voice, UX Copy & Technical Docs",
    description:
      "Highlights conversion-driven copywriting, SEO traffic compounding, style guide creation, and customer onboarding clarity.",
    category: "creative",
    layoutArchetype: "single_column",
    badge: "",
    isPro: false,
    tokenCost: 0,
    defaultTheme: {
      accentColor: "#475569",
      fontFamily: "serif",
      layoutDensity: "normal",
    },
    isActive: true,
    sortOrder: 25,
  },
  {
    slug: "ux-researcher",
    name: "UX Researcher & Strategist",
    subtitle: "Qualitative / Quantitative Usability Studies",
    description:
      "Structures heuristic audits, user cohort testing, SUS scores, and data-backed product roadmap recommendations.",
    category: "creative",
    layoutArchetype: "sidebar_left",
    badge: "",
    isPro: false,
    tokenCost: 0,
    defaultTheme: {
      accentColor: "#059669",
      fontFamily: "sans",
      layoutDensity: "normal",
    },
    isActive: true,
    sortOrder: 26,
  },
  {
    slug: "spatial-3d-designer",
    name: "Spatial & XR Designer",
    subtitle: "VisionOS, AR/VR & 3D Spatial Interfaces",
    description:
      "Showcases spatial UI layout principles, unity shader integration, gesture design patterns, and immersive prototype testing.",
    category: "creative",
    layoutArchetype: "minimal_tech",
    badge: "PRO",
    isPro: true,
    tokenCost: 10,
    defaultTheme: {
      accentColor: "#6366f1",
      fontFamily: "mono",
      layoutDensity: "normal",
    },
    isActive: true,
    sortOrder: 27,
  },

  // ==========================================
  // 28-39: FINANCE, CONSULTING & EXECUTIVE (12 templates)
  // ==========================================
  {
    slug: "executive",
    name: "Executive Classic",
    subtitle: "Management, Finance & Senior Roles",
    description:
      "Refined traditional serif typography, dense high-impact bullet sections, and formal corporate structure favored by senior recruiters.",
    category: "executive",
    layoutArchetype: "executive_classic",
    badge: "",
    isPro: false,
    tokenCost: 0,
    defaultTheme: {
      accentColor: "#0f172a",
      fontFamily: "serif",
      layoutDensity: "normal",
    },
    isActive: true,
    sortOrder: 28,
  },
  {
    slug: "wall-street-analyst",
    name: "Wall Street Analyst",
    subtitle: "M&A, LBO Modeling & Corporate Valuation",
    description:
      "Dense, ultra-structured layout adhering strictly to Goldman Sachs, Morgan Stanley, and J.P. Morgan recruiter formatting rules.",
    category: "executive",
    layoutArchetype: "executive_classic",
    badge: "Wall St.",
    isPro: true,
    tokenCost: 15,
    defaultTheme: {
      accentColor: "#0f172a",
      fontFamily: "serif",
      layoutDensity: "compact",
    },
    isActive: true,
    sortOrder: 29,
  },
  {
    slug: "harvard-ivy-ats",
    name: "Harvard Ivy League ATS",
    subtitle: "The Gold Standard Academic & Corporate Layout",
    description:
      "Modeled directly on the Harvard Office of Career Services resume template. Highest ATS parsing reliability across Fortune 500 portals.",
    category: "executive",
    layoutArchetype: "single_column",
    badge: "Ivy League",
    isPro: false,
    tokenCost: 0,
    defaultTheme: {
      accentColor: "#991b1b",
      fontFamily: "serif",
      layoutDensity: "compact",
    },
    isActive: true,
    sortOrder: 30,
  },
  {
    slug: "strategy-consultant",
    name: "McKinsey Strategy Consultant",
    subtitle: "MBB Case Frameworks & Operational Restructuring",
    description:
      "Built for McKinsey, BCG, and Bain applicants with quantified EBITDA improvements, client scope metrics, and executive summaries.",
    category: "executive",
    layoutArchetype: "executive_classic",
    badge: "PRO",
    isPro: true,
    tokenCost: 15,
    defaultTheme: {
      accentColor: "#1e293b",
      fontFamily: "serif",
      layoutDensity: "normal",
    },
    isActive: true,
    sortOrder: 31,
  },
  {
    slug: "cto-executive",
    name: "Chief Technology Officer (CTO)",
    subtitle: "Board Leadership, Team Scaling & Tech Strategy",
    description:
      "Designed for executive engineering leaders showing headcount scaling (10->150), multi-million cloud budgets, and patent portfolios.",
    category: "executive",
    layoutArchetype: "single_column",
    badge: "Executive",
    isPro: true,
    tokenCost: 15,
    defaultTheme: {
      accentColor: "#312e81",
      fontFamily: "sans",
      layoutDensity: "normal",
    },
    isActive: true,
    sortOrder: 32,
  },
  {
    slug: "vc-private-equity",
    name: "Venture Capital & PE Associate",
    subtitle: "Deal Sourcing, Due Diligence & Portfolio Ops",
    description:
      "Highlights capital deployed ($M), IRR performance, board observer seats, deal flow volume, and founder network reach.",
    category: "executive",
    layoutArchetype: "executive_classic",
    badge: "PRO",
    isPro: true,
    tokenCost: 15,
    defaultTheme: {
      accentColor: "#064e3b",
      fontFamily: "serif",
      layoutDensity: "normal",
    },
    isActive: true,
    sortOrder: 33,
  },
  {
    slug: "quant-trader",
    name: "Quant & Algorithmic Trader",
    subtitle: "High-Frequency Trading & Statistical Arbitrage",
    description:
      "Prioritizes Sharpe ratios, mathematical modeling rigor, latency optimizations, and alpha generation metrics for hedge funds.",
    category: "executive",
    layoutArchetype: "minimal_tech",
    badge: "PRO",
    isPro: true,
    tokenCost: 15,
    defaultTheme: {
      accentColor: "#0f172a",
      fontFamily: "mono",
      layoutDensity: "compact",
    },
    isActive: true,
    sortOrder: 34,
  },
  {
    slug: "cfo-executive",
    name: "Chief Financial Officer (CFO)",
    subtitle: "Capital Allocation, Audit & IPO Governance",
    description:
      "Emphasizes capital raises (Series B/C/IPO), audited financial statements, tax strategy, and cash runway extensions.",
    category: "executive",
    layoutArchetype: "executive_classic",
    badge: "",
    isPro: true,
    tokenCost: 10,
    defaultTheme: {
      accentColor: "#0f172a",
      fontFamily: "serif",
      layoutDensity: "normal",
    },
    isActive: true,
    sortOrder: 35,
  },
  {
    slug: "director-engineering",
    name: "Director of Engineering",
    subtitle: "Multi-Tier Management, Hiring & OKR Execution",
    description:
      "Demonstrates management of managers, retention rates, annual engineering compensation budgets, and product delivery speed.",
    category: "executive",
    layoutArchetype: "single_column",
    badge: "",
    isPro: false,
    tokenCost: 0,
    defaultTheme: {
      accentColor: "#1e3a8a",
      fontFamily: "sans",
      layoutDensity: "normal",
    },
    isActive: true,
    sortOrder: 36,
  },
  {
    slug: "enterprise-sales-cro",
    name: "Enterprise Sales & CRO",
    subtitle: "Quota Attainment, ACV & Fortune 500 Contracts",
    description:
      "Focuses on 150%+ quota attainment records, multi-million dollar ACV deals closed, and sales team hiring/enablement.",
    category: "executive",
    layoutArchetype: "single_column",
    badge: "",
    isPro: false,
    tokenCost: 0,
    defaultTheme: {
      accentColor: "#047857",
      fontFamily: "sans",
      layoutDensity: "normal",
    },
    isActive: true,
    sortOrder: 37,
  },
  {
    slug: "investment-banking",
    name: "Investment Banking Associate",
    subtitle: "Pitchbooks, CIMs & Syndicate Financing",
    description:
      "Standardised single-column financial services template with clear transaction history sections and modeling proficiencies.",
    category: "executive",
    layoutArchetype: "executive_classic",
    badge: "",
    isPro: false,
    tokenCost: 0,
    defaultTheme: {
      accentColor: "#0f172a",
      fontFamily: "serif",
      layoutDensity: "compact",
    },
    isActive: true,
    sortOrder: 38,
  },
  {
    slug: "operations-director",
    name: "Supply Chain & Operations Director",
    subtitle: "Lean Six Sigma, Logistics & Cost Reduction",
    description:
      "Highlights vendor negotiation savings ($M), inventory turnover cycles, automated fulfillment, and global procurement.",
    category: "executive",
    layoutArchetype: "single_column",
    badge: "",
    isPro: false,
    tokenCost: 0,
    defaultTheme: {
      accentColor: "#334155",
      fontFamily: "sans",
      layoutDensity: "normal",
    },
    isActive: true,
    sortOrder: 39,
  },

  // ==========================================
  // 40-50: GENERAL, STARTUPS & EARLY CAREER (11 templates)
  // ==========================================
  {
    slug: "yc-startup-hire",
    name: "Y Combinator Startup Early Hire",
    subtitle: "Seed to Series A • High Velocity & Zero to One",
    description:
      "Built for generalist engineers, growth operators, and early employees who wear multiple hats and execute at breakneck speed.",
    category: "general",
    layoutArchetype: "single_column",
    badge: "YC Style",
    isPro: true,
    tokenCost: 10,
    defaultTheme: {
      accentColor: "#ea580c",
      fontFamily: "sans",
      layoutDensity: "compact",
    },
    isActive: true,
    sortOrder: 40,
  },
  {
    slug: "stanford-academic",
    name: "Stanford Academic Scholar",
    subtitle: "PhD, Postdoc & Technical Publications",
    description:
      "Formatted for university researchers and scientists with dedicated sections for peer-reviewed journals, patents, and grants.",
    category: "general",
    layoutArchetype: "executive_classic",
    badge: "",
    isPro: false,
    tokenCost: 0,
    defaultTheme: {
      accentColor: "#831843",
      fontFamily: "serif",
      layoutDensity: "normal",
    },
    isActive: true,
    sortOrder: 41,
  },
  {
    slug: "cambridge-researcher",
    name: "Cambridge Research Fellow",
    subtitle: "Higher Education & Faculty Appointments",
    description:
      "Traditional UK/European academic curriculum vitae (CV) format with expansive research narratives and thesis advisor notes.",
    category: "general",
    layoutArchetype: "executive_classic",
    badge: "",
    isPro: false,
    tokenCost: 0,
    defaultTheme: {
      accentColor: "#0f172a",
      fontFamily: "serif",
      layoutDensity: "normal",
    },
    isActive: true,
    sortOrder: 42,
  },
  {
    slug: "career-pivot-switcher",
    name: "Career Transition & Pivot",
    subtitle: "Bootcamp Grads & Cross-Industry Switchers",
    description:
      "Emphasizes transferable skills, capstone project repos, and fast-learning agility over non-relevant historical job titles.",
    category: "general",
    layoutArchetype: "single_column",
    badge: "Beginner",
    isPro: false,
    tokenCost: 0,
    defaultTheme: {
      accentColor: "#4f46e5",
      fontFamily: "sans",
      layoutDensity: "normal",
    },
    isActive: true,
    sortOrder: 43,
  },
  {
    slug: "college-graduate-tech",
    name: "College Graduate & Entry Tech",
    subtitle: "CS Degrees, Internships & Hackathons",
    description:
      "Places Education and Academic Coursework prominently at the top, supported by hackathon prizes and technical side-projects.",
    category: "general",
    layoutArchetype: "single_column",
    badge: "New Grad",
    isPro: false,
    tokenCost: 0,
    defaultTheme: {
      accentColor: "#0284c7",
      fontFamily: "sans",
      layoutDensity: "normal",
    },
    isActive: true,
    sortOrder: 44,
  },
  {
    slug: "remote-nomad-pro",
    name: "Remote Nomad Professional",
    subtitle: "Async Communication & Distributed Teams",
    description:
      "Highlights asynchronous collaboration tools, timezone flexibility, independent problem-solving, and documented remote workflows.",
    category: "general",
    layoutArchetype: "sidebar_left",
    badge: "Remote",
    isPro: true,
    tokenCost: 10,
    defaultTheme: {
      accentColor: "#059669",
      fontFamily: "sans",
      layoutDensity: "normal",
    },
    isActive: true,
    sortOrder: 45,
  },
  {
    slug: "tpm-leader",
    name: "Technical Program Manager (TPM)",
    subtitle: "Cross-Org Initiatives, Roadmaps & Milestones",
    description:
      "Structures complex multi-team initiatives, risk mitigation matrices, critical path delivery, and vendor management.",
    category: "general",
    layoutArchetype: "single_column",
    badge: "",
    isPro: false,
    tokenCost: 0,
    defaultTheme: {
      accentColor: "#475569",
      fontFamily: "sans",
      layoutDensity: "normal",
    },
    isActive: true,
    sortOrder: 46,
  },
  {
    slug: "bioinformatics-specialist",
    name: "Bioinformatics & Biotech Specialist",
    subtitle: "Genomics, Clinical Trials & Wet Lab Stacks",
    description:
      "Tailored for biotech professionals combining computational analysis (R, Python, Bioconductor) with clinical trial validation.",
    category: "general",
    layoutArchetype: "single_column",
    badge: "Specialized",
    isPro: true,
    tokenCost: 10,
    defaultTheme: {
      accentColor: "#0d9488",
      fontFamily: "sans",
      layoutDensity: "compact",
    },
    isActive: true,
    sortOrder: 47,
  },
  {
    slug: "agile-scrum-master",
    name: "Agile Coach & Scrum Master",
    subtitle: "Sprint Velocity, Retrospectives & JIRA Workflows",
    description:
      "Focuses on sprint burndown metrics, cycle time improvements, team happiness metrics, and scaled agile (SAFe) delivery.",
    category: "general",
    layoutArchetype: "sidebar_left",
    badge: "",
    isPro: false,
    tokenCost: 0,
    defaultTheme: {
      accentColor: "#0284c7",
      fontFamily: "sans",
      layoutDensity: "normal",
    },
    isActive: true,
    sortOrder: 48,
  },
  {
    slug: "customer-success-architect",
    name: "Customer Success Architect",
    subtitle: "Net Revenue Retention (NRR) & Enterprise Onboarding",
    description:
      "Highlights gross and net retention percentages, CSAT/NPS scores, executive QBR presentations, and churn prevention.",
    category: "general",
    layoutArchetype: "single_column",
    badge: "",
    isPro: false,
    tokenCost: 0,
    defaultTheme: {
      accentColor: "#2563eb",
      fontFamily: "sans",
      layoutDensity: "normal",
    },
    isActive: true,
    sortOrder: 49,
  },
  {
    slug: "swiss-monochrome",
    name: "Swiss International Monochrome",
    subtitle: "International Typographic Style • Black & White ATS",
    description:
      "Pure, unadorned Swiss modernist grid layout. Zero color distraction, impeccable baseline grid alignment, and maximum contrast.",
    category: "general",
    layoutArchetype: "single_column",
    badge: "Minimalist",
    isPro: false,
    tokenCost: 0,
    defaultTheme: {
      accentColor: "#0f172a",
      fontFamily: "sans",
      layoutDensity: "normal",
    },
    isActive: true,
    sortOrder: 50,
  },
];
